/*
 * uart_linkingconfig.h
 *
 * Created: 10/23/2023 3:36:26 PM
 *  Author: nadeen.adel
 */ 


#ifndef UART_LINKINGCONFIG_H_
#define UART_LINKINGCONFIG_H_

/*USART SYNCHRONIZATION MODE OPTIONS:
USART_ASYNC_MODE      
 USART_SYNC_MODE      
*/
typedef enum EN_USART_SET_MODE{
	USART_ASYNC_MODE=0,
	USART_SYNC_MODE
	}EN_USART_SET_MODE;
	
	
/*USART SPEED MODE OPTIONS:
 USART_NORMAL_SPEED   
 USART_DOUBLE_SPEED    
*/
typedef enum EN_USART_SET_SPEED{
 USART_NORMAL_SPEED=0,   
 USART_DOUBLE_SPEED    
}EN_USART_SET_SPEED;


/*USART PARITY OPTIONS :
USART_NO_PARITY
USART_ODD_PARITY
USART_EVEN_PARITY
*/
typedef enum EN_USART_SET_PARITY{
 USART_NO_PARITY=0,
 USART_ODD_PARITY,
 USART_EVEN_PARITY
}EN_USART_SET_PARITY;


/*USART DATA SIZE OPTIONS :
 USART_DATA_SIZE_5     
 USART_DATA_SIZE_6     
 USART_DATA_SIZE_7
 USART_DATA_SIZE_8     
 USART_DATA_SIZE_9     
*/
typedef enum EN_USART_SET_DATA_SIZE{
	 USART_DATA_SIZE_5=0,
	 USART_DATA_SIZE_6,
	 USART_DATA_SIZE_7,
	 USART_DATA_SIZE_8,
	 USART_DATA_SIZE_9
	}EN_USART_SET_DATA_SIZE;


/*USART STOP BITS OPTIONS :
 USART_ONE_STOP_BIT    
 USART_TWO_STOP_BITS
*/
typedef enum EN_USART_SET_STOP_BITS{
	USART_ONE_STOP_BIT=0,
	USART_TWO_STOP_BITS
	}EN_USART_SET_STOP_BITS;
	
	
/*USART BAUD RATE OPTIONS
 BAUD_2400          
 BAUD_4800          
 BAUD_9600          
 BAUD_14400        
 BAUD_19200               
*/
typedef enum EN_USART_SET_BAUD_RATE{
	 BAUD_2400=2400,
	 BAUD_4800=4800,
	 BAUD_9600=9600,
	 BAUD_14400=14400,
	 BAUD_19200=19200
}EN_USART_SET_BAUD_RATE;



/*CPU FREQUENCY OPTIONS
 FCPU_4MHZ         
 FCPU_8MHZ         
 FCPU_16MHZ        
*/
typedef enum EN_USART_SET_FCPU{
	FCPU_4MHZ=4000000,
	FCPU_8MHZ=8000000,
	FCPU_16MHZ=16000000
	}EN_USART_SET_FCPU;
	
typedef struct ST_USART_CONFIG{
		
		EN_USART_SET_MODE  SYNC_MODE;
		EN_USART_SET_FCPU FCPU;
		EN_USART_SET_BAUD_RATE BAUD_RATE;
		EN_USART_SET_SPEED SPEED_MODE;
		EN_USART_SET_PARITY PARITY_MODE;
		EN_USART_SET_STOP_BITS STOP_BIT;
		EN_USART_SET_DATA_SIZE DATA_SIZE;
		
	}ST_USART_CONFIG;

	
	
#endif /* UART_LINKINGCONFIG_H_ */