/*
 * uart_config.h
 *
 * Created: 10/15/2023 12:54:06 PM
 *  Author: nadeen.adel
 */ 


#ifndef UART_CONFIG_H_
#define UART_CONFIG_H_



/*USART SYNCHRONIZATION MODE OPTIONS:
USART_ASYNC_MODE      
 USART_SYNC_MODE      
*/
#define  USART_SET_SYNCH_MODE   USART_SYNC_MODE       


/*USART SPEED MODE OPTIONS:
 USART_NORMAL_SPEED   
 USART_DOUBLE_SPEED    
*/
#define  USART_SET_SPEED   USART_NORMAL_SPEED    


/*USART PARITY OPTIONS :
USART_NO_PARITY
USART_ODD_PARITY
USART_EVEN_PARITY
*/
#define USART_SET_PARITY_MODE      USART_EVEN_PARITY

/*USART DATA SIZE OPTIONS :
 USART_DATA_SIZE_5     
 USART_DATA_SIZE_6     
 USART_DATA_SIZE_7
 USART_DATA_SIZE_8     
 USART_DATA_SIZE_9     
*/
#define USART_SET_DATA_SIZE        USART_DATA_SIZE_8

/*USART STOP BITS OPTIONS :
 USART_ONE_STOP_BIT    
 USART_TWO_STOP_BITS
*/
#define USART_SET_STOP_BITS       USART_TWO_STOP_BITS


/*USART BAUD RATE OPTIONS
 BAUD_2400          
 BAUD_4800          
 BAUD_9600          
 BAUD_14400        
 BAUD_19200        
 BAUD_28800        
 BAUD_38400        
*/
#define USART_SET_BAUD_RATE       BAUD_9600

/*CPU FREQUENCY OPTIONS
 FCPU_4MHZ         
 FCPU_8MHZ         
 FCPU_16MHZ        
*/
#define USART_SET_FCPU           FCPU_8MHZ

#define ASYNC_NORMAL_EQU               ((USART_SET_FCPU/(16*USART_SET_BAUD_RATE))-1)
#define ASYNC_DOUBLE_EQU               ((USART_SET_FCPU/(4*USART_SET_BAUD_RATE))-1)
#define SYNC_EQU               ((USART_SET_FCPU/(2*USART_SET_BAUD_RATE))-1)






#endif /* UART_CONFIG_H_ */